### ISSUE TITLE
iOS 3.64 Apple Store release - Battery consumption - default settings

### ISSUE THREAD

**Issue by jodsmithLT** [teddyhoo/IOS-Sitter-Mobile#11]
I have heard from a couple businesses that the updated app is consuming more battery life. 
Pets R US has a couple Sitters who were using it last week and a couple went back to using the Mobile web version to save battery life. 
I have suggested that they view the training video to reset the settings

It would be great to have the default settings in the iOS app to be a little more efficient, if possible.

**Comment by teddyhoo** [comment]
I am testing a build right now where the GPS tracking is only running when you are actually on a visit. The gps consumption profile has been reduced. And it seems to be working properly. There are several transition points, so they just need to be accounted for and tested but the on/off location tracking is good.

**Comment by teddyhoo** [comment]
Latest TestFlight build turns GPS on / off (when arrived status on any visit / when no visit arrived).

**Comment by teddyhoo** [comment]
![img_1119](https://user-images.githubusercontent.com/5602683/45259192-aa63d080-b394-11e8-83b2-0fad870fcf03.png)

**Comment by teddyhoo** [comment]
![img_1118](https://user-images.githubusercontent.com/5602683/45259199-ed25a880-b394-11e8-9e91-354531739106.png)
