### ISSUE TITLE
Alarm field truncated

### ISSUE THREAD

**Issue by jodsmithLT** [teddyhoo/IOS-Sitter-Mobile#12]
This is from JJ at Dog walking DC. iPhone X. 3.65 build 1

![image](https://user-images.githubusercontent.com/41838025/45191442-db16ff00-b208-11e8-9aec-5f96c58158c1.png)

**Comment by teddyhoo** [comment]
Representative test of a long Alarm Info field that is rendered on 3 different device sizes (5,6,6p -- 7,8 are same as 6, 7p,8p are same as 6p). They are properly formatted so we need to know specific version and device where she experienced this issue. 


<img width="1046" alt="screen shot 2018-09-10 at 1 51 33 pm" src="https://user-images.githubusercontent.com/5602683/45314868-ed42b700-b500-11e8-89f1-98f8b3d04a87.png">

**Comment by jodsmithLT** [comment]
Version 3.65 build 1
Still able to reproduce this on iPhone X.  Tonka Test, Client Charlie Brown(Snoopy) Sitter iPhone.
iPhone 6 displays fine.

iPhone X
![image](https://user-images.githubusercontent.com/41838025/48910420-8a8d6600-ee35-11e8-9223-87fe9648cf23.png)

Exact content is:
Please use combination on inner door and the outer door should be closed but remain unlocked.  CLOSE YARD GATE PlEASE WHEN YOU LEAVE  Front Door opens with combination 3276. when dog is in basement unit, entrance to lower units is 6816 and the front unit is 7168

**Comment by jodsmithLT** [comment]
I have updated the information on JJ's phone.

**Comment by teddyhoo** [comment]
Consolidated
