### ISSUE TITLE
Pet names are writing over Note Icons

### ISSUE THREAD

**Issue by jodsmithLT** [teddyhoo/IOS-Sitter-Mobile#14]
Below you can see that when there are a lot of pets or long names that the Sitter can no longer have access to the Note icons.

Client Creature Conforts AZ. Client Kinsey

![image](https://user-images.githubusercontent.com/41838025/45600887-c6392900-b9c9-11e8-876a-29f5a18e6fde.png)

**Comment by jodsmithLT** [comment]
Wrong Device - duplicated into Android

**Comment by teddyhoo** [comment]
This is an Android screenshot. And it should be fixed in the current version of the app.
