### ISSUE TITLE
Truncated Pet Notes field on iPhone X v3.65 build 1

### ISSUE THREAD

**Issue by jodsmithLT** [teddyhoo/IOS-Sitter-Mobile#19]
I am not able to reproduce this issue on my iPhone 6, but JJ from DWDC is having this issue on the iPhone X

![image](https://user-images.githubusercontent.com/41838025/46315863-32a05480-c594-11e8-996a-83d98c84fc6e.png)

**Comment by jodsmithLT** [comment]
My iPhone 6 must be just a bit wider than the X? I cut/pasted the text into one of my test pet profiles.

![image](https://user-images.githubusercontent.com/41838025/46573959-115bb180-c962-11e8-838f-0496437fd5a0.png)

**Comment by teddyhoo** [comment]
https://github.com/teddyhoo/IOS-Sitter-Mobile/issues/34

**Comment by teddyhoo** [comment]
https://github.com/teddyhoo/IOS-Sitter-Mobile/issues/31

**Comment by teddyhoo** [comment]
https://github.com/teddyhoo/IOS-Sitter-Mobile/issues/27

**Comment by jodsmithLT** [comment]
So you are saying that visits not showing on the Home screen - #34 is due to phone formating?

**Comment by jodsmithLT** [comment]
Tested on my iPhone X it is still truncating the Pet "Notes" field under the Pet profile data. Tonka Test: Client Rick Castle: Pet Lily: Notes under her profile were copied from Jordan's Pet Care - client Matthew Markoff.  The iPhone app is cutting off the last line.

**Comment by jodsmithLT** [comment]
Still a huge issue: Dogwalking DC: Ticket 21133

![image](https://user-images.githubusercontent.com/41838025/52882437-473d4d80-312d-11e9-8d47-06d9a849f9df.png)

**Comment by jodsmithLT** [comment]
IS not showing as an issue in TestFlight version 4(25)
