### ISSUE TITLE
Visit Completion not transmitted, photo delayed

### ISSUE THREAD

**Issue by mattleashtime** [teddyhoo/IOS-Sitter-Mobile#21]
Sitter says she marked completion and it looked normal, but it did not register.  24 minutes after visit report, photo had not yet arrived.

User: Sandy Getchell-White [login: sandy@purrfectplaceforpets.com]

LEASHTIME IOS 11 / ver: 3.65 / build:1
Visit: 83763 Cat only visits 1 - 2 cats 5p-7p
Arrival marked and received at 7:01 pm
Visit report received at 7:30:50 pm
Last MV tracked at 7:32 pm
Completion NOT recorded on server as marked by mobile.
Completion marked at 7:54 pm
Photo present when examined by matt next day at 9:30 am.

### Help Desk Ticket

https://leashtime.com/support/admin/admin_ticket.php?track=9U2-DR3-XJJD

_So again, or still the app for I Phone is not working well. It's very
embarrassing when at a new clients house when you can't even get it to
open.

Just got back from a visit for Lambert-took a picture and everything
seemed to be working. I look at the web page-job not marked complete,
no picture but all notes are there. This thing drives all of my
sitters and me nuts I have to say.

Sandy_

**Comment by teddyhoo** [comment]
Ticket consolidated for requests that do not reliably transmit and failover procedures.
