### ISSUE TITLE
Home Info is missing Field Titles v3.65

### ISSUE THREAD

**Issue by jodsmithLT** [teddyhoo/IOS-Sitter-Mobile#23]
As shown below. Field Titles are missing. Data is there, but the titles are missing.

![image](https://user-images.githubusercontent.com/41838025/46972106-6181f480-d083-11e8-9619-90f3a376df3f.png)

**Comment by jodsmithLT** [comment]
Cheryl from Critter Sitters MD: Also reported an example of how it confuses the staff:

 Home Info has:

Leash / Pet Carrier Location: Stairs near front door
Food Location: Pantry near bathroom
Parking Info: driveway

But in the app, you will only see:

Home Info:
Stairs near front door
Pantry near bathroom
driveway

Which leaves the sitters confused and guessing.

**Comment by jodsmithLT** [comment]
This only appears to be an issue on the iPhone version

**Comment by teddyhoo** [comment]
Consolidated
