### ISSUE TITLE
Cancellation/Change Pending

### ISSUE THREAD

**Issue by jodsmithLT** [teddyhoo/IOS-Sitter-Mobile#24]
This would be for both Android and iOS apps.  On the apps the Sitter is no longer seeing the Cancellation or Change pending note for a visit. On the Mobile web app the sitter is shown that right next to the service name on the main page.  This function is super helpful for those that are in the field working or for last minute cancellations.

![image](https://user-images.githubusercontent.com/41838025/47222075-832cf580-d37b-11e8-8279-3f63d1881a08.png)

**Comment by teddyhoo** [comment]
Consolidated
