### ISSUE TITLE
Not all Pet profile icons showing up iPhone 6 vs. iPhone X. 3.65 build 1

### ISSUE THREAD

**Issue by jodsmithLT** [teddyhoo/IOS-Sitter-Mobile#27]
DB: LMPS, Client Carrier 11/22/2018 Sitter Jody.
Same client same day

When I log in using my iPhone 6 only 3 pet icons show up on top (they have 5 pets)
![image](https://user-images.githubusercontent.com/41838025/48911017-2cfa1900-ee37-11e8-95c5-99ef6d58a0f6.png)

iPhone X:
![image](https://user-images.githubusercontent.com/41838025/48911085-65015c00-ee37-11e8-934b-aadb5ca49a80.png)

**Comment by teddyhoo** [comment]
Consolidated
