### ISSUE TITLE
Truncated Garage Code field - v3.65 B1

### ISSUE THREAD

**Issue by jodsmithLT** [teddyhoo/IOS-Sitter-Mobile#28]
I ran into an issue at a clients house the other day. Since I was unable to see all the data, I had to login with my admin account - web browser. I could have used the Mobile Web app too.

Content should be:
Garge Code: 5929 for front door and Garage door

My iPhone X displays:
![image](https://user-images.githubusercontent.com/41838025/48911216-dccf8680-ee37-11e8-8216-32065b3787f3.png)

My iPhone 6 displays:
![image](https://user-images.githubusercontent.com/41838025/48911361-3932a600-ee38-11e8-93f6-539e086ba834.png)

**Comment by teddyhoo** [comment]
Consolidated
