### ISSUE TITLE
Emergency and Trusted Neighbor "HAS KEY" field  mis-reported 

### ISSUE THREAD

**Issue by mattleashtime** [teddyhoo/IOS-Sitter-Mobile#30]

**Comment by mattleashtime** [comment]
https://leashtime.com/support/admin/admin_ticket.php?track=6XT-GSA-1X92

In the iPhone app, "HAS KEY" is reported as YES, when the actual value is "No".  Both for Emergency and Trusted Neighbor.

Confirmed this for sitter "coldstream.cheryl@gmail.com" with client "Cheryl Schaible".

Confirmed that the correct values are coming from the server:

"emergency":{"name":"Mary Ellen Roberson ","location":"6585 Nyasa Bend, right behind us.","homephone":"301-865-5447","workphone":"","cellphone":"240-344-3119","note":"","haskey":"No"},
"neighbor":{"name":".","location":"","homephone":"","workphone":"","cellphone":"","note":"","haskey":"No"}

Confirmed this is NOT a problem in ANDROID.

**Comment by teddyhoo** [comment]
Consolidated
