### ISSUE TITLE
iPhone Xs - Not showing future days

### ISSUE THREAD

**Issue by jodsmithLT** [teddyhoo/IOS-Sitter-Mobile#31]
Ticket #20696

Gayle with TLC Pet Sitting is not seeing her visits on future days. I asked her to try a couple things and even let it sit for a bit and that still did not work.
I am not able to reproduce this on my iphone X.

LEASHTIME IOS 11 / ver: 3.65 / build:1

![image](https://user-images.githubusercontent.com/41838025/50316771-b1af7580-047d-11e9-9569-3e14e90bc3c4.png)

**Comment by teddyhoo** [comment]
Consolidated
