### ISSUE TITLE
iPhone Xs not showing today's visits.

### ISSUE THREAD

**Issue by jodsmithLT** [teddyhoo/IOS-Sitter-Mobile#34]
Sitter: Gayle from TLC is not able to see her visits on today's date.
Screen shots of phone info and the app for today. She has 2 visits for today, the third visit is canceled.

![image](https://user-images.githubusercontent.com/41838025/50613449-339e9600-0ea3-11e9-8d39-90cf6eb9c966.png)

![image](https://user-images.githubusercontent.com/41838025/50613528-68aae880-0ea3-11e9-871c-b322f721e567.png)

**Comment by teddyhoo** [comment]
Consolidating iPhone model sizing issues into single ticket.
