### ISSUE TITLE
Service Name not showing up on APP v4 (b3)

### ISSUE THREAD

**Issue by jodsmithLT** [teddyhoo/IOS-Sitter-Mobile#40]
DB: Lake Minnetonka Pet Sitters
4/8/2019 Client Stacy Voves - Winston.

The service name is: "As Needed Dog Walk, 1 dog" Does not display

![image](https://user-images.githubusercontent.com/41838025/55760450-bc3c4d80-5a21-11e9-88c6-0302a1796355.png)

**Comment by jodsmithLT** [comment]
Appears we have a limit on the Service name length.

**Comment by teddyhoo** [comment]
For platforms, field height is doubled and number lines = 2 when length of a field (pet name, client name, service) is greater than certain length (platform dependent). 

This is fixed.
