### ISSUE TITLE
iPhone 5s or 5 issue 

### ISSUE THREAD

**Issue by jodsmithLT** [teddyhoo/IOS-Sitter-Mobile#5]
Users are not able to see the Envelope on the Visit Report screen.  Using the version 3.63. I am not able to test on 3.64. I have the iPhone 6.

**Comment by teddyhoo** [comment]
I am not sure where along the line this got fixed but it is good to go in 3.64. Attached is screen shot from the 5 simulator. I ran through UI tests for all the platforms and we are good to go. 
<img width="320" alt="screen shot 2018-08-21 at 7 07 00 pm" src="https://user-images.githubusercontent.com/5602683/44433691-6f306780-a575-11e8-89eb-fac5db28ef84.png">

**Comment by jodsmithLT** [comment]
203 Pets has a sitter with an iPhone 5 - ticket 19773. Waiting for release to finally reply to ticket

**Comment by teddyhoo** [comment]
I assume you replied to the ticket and we can close this bug ticket

**Comment by jodsmithLT** [comment]
Client with 3.64 build 10 and the 5s is still not able to see the Visit report envelope.
Ticket #2000.
I am still waiting to hear back from 203 pets.  ticket 19773
