### ISSUE TITLE
Map function in the Visit report TestFlight v4(24)

### ISSUE THREAD

**Issue by jodsmithLT** [teddyhoo/IOS-Sitter-Mobile#52]
Maybe I am just not looking in the right place?

**Comment by teddyhoo** [comment]
This is available but only after marking arrive for visit. That logic actually does not make sense. If you have arrived at home, why would you need directions. Will surface it up a layer prior to marking arrive.

**Comment by jodsmithLT** [comment]
Still an issue in version 4(10)

**Comment by jodsmithLT** [comment]
Can be accessed via the Visit report before marking Arrived.

**Comment by jodsmithLT** [comment]
Can be accessed befoe the visit is marked arrive
