### ISSUE TITLE
No Close or return button on the Clients Profile - TestFlight v4(8)

### ISSUE THREAD

**Issue by jodsmithLT** [teddyhoo/IOS-Sitter-Mobile#53]
This may be an iPhone X issue, but I no longer can see a back arrow on the top left corner of the screen. I just keep hitting in the white space and it closes the screen.

![image](https://user-images.githubusercontent.com/41838025/62497990-4d8ab900-b7a3-11e9-9455-ac6685e620dc.png)

**Comment by teddyhoo** [comment]
Yes, it is X issue. It has been fixed. In the meantime the button is there but you cannot see it because it is same color as background.
