### ISSUE TITLE
Visit Report does not list the Client Name - TestFlight v 4(8)

### ISSUE THREAD

**Issue by jodsmithLT** [teddyhoo/IOS-Sitter-Mobile#55]
One of the prior TF versions 4 did, but now when I am in the Visit report I do not see the Clients or the Pets name. This is a problem when you have multiple visits and or you just want to make sure you are talking about the correct pet. 

![image](https://user-images.githubusercontent.com/41838025/62498611-6b591d80-b7a5-11e9-87c5-3f7ecba3899d.png)

**Comment by teddyhoo** [comment]
fixed.
