### ISSUE TITLE
Test Flight v4(20) - Visit report problems

### ISSUE THREAD

**Issue by jodsmithLT** [teddyhoo/IOS-Sitter-Mobile#64]
Once I have marked a visit complete (and the app crashes) once I go back into the Visit Report. Data is missing. See the graphic below.
![image](https://user-images.githubusercontent.com/41838025/71450259-08502f00-2724-11ea-8202-568682a682c4.png)

**Comment by jodsmithLT** [comment]
One of the visits recently did,  I forgot to attach the photo and I had no way of going in and attaching the photo and resending the report.

**Comment by teddyhoo** [comment]
Preview step has been addede

**Comment by jodsmithLT** [comment]
Fixed
