### ISSUE TITLE
Pet Profile data v3.64 build 10

### ISSUE THREAD

**Issue by jodsmithLT** [teddyhoo/IOS-Sitter-Mobile#8]
Pet Profile data: TonkaTEST Client:Rick Castle Pet: Deacon

The description field is showing up after the NOTES section.
The Custom pet fields are a little mixed up. It does not match the web version I could not see a real pattern. The checkbox fields end all at the bottom.

**Comment by teddyhoo** [comment]
The pet fields come in format:

petCustom1
petCustom2

I sort by those key criteria. Matt says that they may be labeled as above but that does not mean they are in that order on the server. If he sends me petCustom1 ... and it means #1 then it is already supposed to sort properly.

**Comment by jodsmithLT** [comment]
So you are telling me we have no way of correcting the order of the Pet Custom fields, as we are not labeling them properly?
I was not sure what the question to me is?

**Comment by teddyhoo** [comment]
Matt and I discussed and he should be writing a sort on the server end.

**Comment by teddyhoo** [comment]
Consolidated
